### ISSUE TITLE
Watchlist and Favorites

### ISSUE THREAD

**Issue by MSoup** [mochi-stream/mochi#22]
Allow users to create a watchlist and mark their favorite anime.

**Comment by MSoup** [comment]
Began working on this task at branch `daven/add-watchlist-button`

Completed: Button UI
TODO: Figure out the best way to keep watchList state (maybe need to peek into supabase soon)

**Comment by swargaraj** [comment]
My idea was, when we will fetch the user, we will also fetch all the Collection[] related to the user. Collection[] will only contain the animeId (anilist id) userID and status. Then in frontend we will filter based on status then get the images from anilist on client end.
